# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81bddbe49e4f5e123526953ea1536329a52f5ca9905756411701ba7d79db8a518fba65a34d303bbdafd14018206b3a776ae94ab3e50f61a13d917de2f65f29c3

test:
  secret_key_base: 7cd0d140abd3dc6cfc2de6f070bf64d0faa2ad2eb4e0e0159088e7850c1fdbdac29e258990b2d790fbf88563c4e6c56707eef8ab7a77fcd576b069cdcb5bf643

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
